#!/bin/sh

flags="$PX2C_FLAGS"

flag() {
    f=$1; shift
    t=$1; shift
    while [ -n "$1" ]; do
        eval "ev=\"\$PX2C_$1\""
        if [ -n "$ev" ]; then
            case "$t" in
            1) flags="$flags $f"            ;;
            p) ev="ext/$ev"; flags="$flags $f /${ev#*//}" ;;
            q) flags="$flags $f \"$ev\""    ;;
            *) flags="$flags $f $ev"        ;;
            esac
        fi
        shift
    done
}

flag -p                 s   P PORT
flag -t                 s   T TIMEOUT
flag -a                 q   A USER_AGENT
flag -c                 1   C ACCEPT_CONNECT
flag -4                 1   4 FORCE_IPV4
flag -b                 s   B BACKLOG
flag -s                 1   S FORCE_HTTPS
flag --proxy            s   PROXY
flag --api              s   API
flag --api-usage        s   API_USAGE
flag --api-auth-ua      q   API_AUTH_UA
flag --api-dat-ua       q   API_DAT_UA
flag --api-auth-xua     q   API_AUTH_XUA
flag --api-dat-xua      q   API_DAT_XUA
flag --api-server       s   API_SERVER
flag --api-override     1   API_OVERRIDE
flag --direct-dat       1   DIRECT_DAT
flag --bbsmenu          q   BBSMENU
flag --chunked          1   CHUNKED
flag --bbscgi-header    q   BBSCGI_HEADER
flag --bbscgi-header    q   BBSCGI_HEADER2 BBSCGI_HEADER3 BBSCGI_HEADER4 BBSCGI_HEADER5
flag --bbscgi-header    q   BBSCGI_HEADER6 BBSCGI_HEADER7 BBSCGI_HEADER8 BBSCGI_HEADER9
flag --bbscgi-postorder q   BBSCGI_POSTORDER
flag --bbscgi-utf8      s   BBSCGI_UTF8
flag --bbscgi-lua       p   BBSCGI_LUA
flag --gikofix          1   GIKOFIX
flag --keystore         p   KEYSTORE
flag --mitm             s   MITM
flag --mitm-ca-cert     p   MITM_CA_CERT
flag --mitm-ca-key      p   MITM_CA_KEY
flag --subject-to-lastmodify    1   SUBJECT_TO_LASTMODIFY

if [ -n "$PX2C_BBSCGI_REMOVE_HEADERS" ]; then
    for h in $PX2C_BBSCGI_REMOVE_HEADERS; do
        flags="$flags --bbscgi-header \"$h:\""
    done
fi

if [ -n "$PX2C_MITM_CA_PEM" ]; then
    f="/ext/$PX2C_MITM_CA_PEM"
    if [ ! -e "$f" ]; then
        mkdir -p `dirname "$f"`
        proxy2ch --mitm-certgen > "$f"
        flags="$flags --mitm-ca-cert $f --mitm-ca-key $f"
    fi
fi

exec /usr/local/bin/proxy2ch --verbose -g $flags
